export const MOODS = {
  OVERJOYED: {
    id: "overjoyed",
    label: "Çok Mutlu",
    emoji: "🤗",
    score: 10,
    color: "yellow",
    prompt: "Bugün ne gibi harika şeyler oldu?",
    pixabayQuery: "joyful+celebration+happy",
  },
  ACCOMPLISHED: {
    id: "accomplished",
    label: "Başarılı",
    emoji: "⭐",
    score: 9,
    color: "amber",
    prompt: "Neyi başardınız?",
    pixabayQuery: "achievement+success+star",
  },
  INSPIRED: {
    id: "inspired",
    label: "İlham Verici",
    emoji: "💫",
    score: 9,
    color: "violet",
    prompt: "Yaratıcılığınızı ne tetikliyor?",
    pixabayQuery: "inspiration+creative+light",
  },
  PROUD: {
    id: "proud",
    label: "Gururlu",
    emoji: "🦁",
    score: 9,
    color: "amber",
    prompt: "Hangi başarıdan gurur duyuyorsunuz?",
    pixabayQuery: "achievement+success+proud",
  },
  LOVED: {
    id: "loved",
    label: "Sevilen",
    emoji: "🥰",
    score: 9,
    color: "pink",
    prompt: "Sizi kim veya ne sevindiriyor?",
    pixabayQuery: "love+heart+affection",
  },
  APPRECIATED: {
    id: "appreciated",
    label: "Takdir Edilen",
    emoji: "💝",
    score: 8,
    color: "rose",
    prompt: "Size kim takdir gösterdi?",
    pixabayQuery: "appreciation+gratitude+heart",
  },
  MOTIVATED: {
    id: "motivated",
    label: "Motivasyonlu",
    emoji: "🎯",
    score: 8,
    color: "emerald",
    prompt: "Sizi ileriye ne itiyor?",
    pixabayQuery: "motivation+target+goal",
  },
  HAPPY: {
    id: "happy",
    label: "Mutlu",
    emoji: "😊",
    score: 8,
    color: "amber",
    prompt: "Bugün sizi ne gülümsetiyor?",
    pixabayQuery: "happy+smile+sunshine",
  },
  EXCITED: {
    id: "excited",
    label: "Heyecanlı",
    emoji: "🎉",
    score: 8,
    color: "orange",
    prompt: "Neyi dört gözle bekliyorsunuz?",
    pixabayQuery: "excited+energetic+celebration",
  },
  CONFIDENT: {
    id: "confident",
    label: "Kendine Güvenen",
    emoji: "💪",
    score: 8,
    color: "emerald",
    prompt: "Kendinize güveninizi ne artırıyor?",
    pixabayQuery: "confident+strong+power",
  },
  GRATEFUL: {
    id: "grateful",
    label: "Minnettar",
    emoji: "🙏",
    score: 8,
    color: "green",
    prompt: "Bugün ne için minnettarsınız?",
    pixabayQuery: "grateful+thankful+blessing",
  },
  CONNECTED: {
    id: "connected",
    label: "Bağlantılı",
    emoji: "🤝",
    score: 8,
    color: "indigo",
    prompt: "Bugün sizi kim bağlantılı hissettirdi?",
    pixabayQuery: "connection+together+community",
  },
  PEACEFUL: {
    id: "peaceful",
    label: "Huzurlu",
    emoji: "😌",
    score: 7,
    color: "blue",
    prompt: "Size huzur veren nedir?",
    pixabayQuery: "peaceful+calm+serene",
  },
  HOPEFUL: {
    id: "hopeful",
    label: "Umutlu",
    emoji: "🌱",
    score: 7,
    color: "green",
    prompt: "Size umut veren nedir?",
    pixabayQuery: "hope+growth+spring",
  },
  CREATIVE: {
    id: "creative",
    label: "Yaratıcı",
    emoji: "🎨",
    score: 7,
    color: "violet",
    prompt: "Yaratıcılığınızı ne ilham veriyor?",
    pixabayQuery: "creative+art+inspiration",
  },
  THOUGHTFUL: {
    id: "thoughtful",
    label: "Düşünceli",
    emoji: "🤔",
    score: 6,
    color: "slate",
    prompt: "Aklınızda ne var?",
    pixabayQuery: "thinking+contemplation+reflection",
  },
  CURIOUS: {
    id: "curious",
    label: "Meraklı",
    emoji: "🧐",
    score: 6,
    color: "teal",
    prompt: "İlginizi ne çekti?",
    pixabayQuery: "curious+discovery+explore",
  },
  NOSTALGIC: {
    id: "nostalgic",
    label: "Nostaljik",
    emoji: "🌅",
    score: 5,
    color: "fuchsia",
    prompt: "Hangi anıları düşünüyorsunuz?",
    pixabayQuery: "nostalgia+memories+sunset",
  },
  NEUTRAL: {
    id: "neutral",
    label: "Nötr",
    emoji: "😐",
    score: 5,
    color: "gray",
    prompt: "Gününüz nasıl geçti?",
    pixabayQuery: "neutral+balance+calm",
  },
  RESTLESS: {
    id: "restless",
    label: "Huzursuz",
    emoji: "🌊",
    score: 4,
    color: "blue",
    prompt: "Sizi huzursuz eden nedir?",
    pixabayQuery: "restless+waves+motion",
  },
  TIRED: {
    id: "tired",
    label: "Yorgun",
    emoji: "😴",
    score: 4,
    color: "purple",
    prompt: "Enerjinizi ne tüketiyor?",
    pixabayQuery: "tired+sleep+rest",
  },
  OVERWHELMED: {
    id: "overwhelmed",
    label: "Bunalmış",
    emoji: "😵",
    score: 3,
    color: "sky",
    prompt: "Size fazla gelen nedir?",
    pixabayQuery: "overwhelmed+chaos+storm",
  },
  ANXIOUS: {
    id: "anxious",
    label: "Endişeli",
    emoji: "😰",
    score: 3,
    color: "indigo",
    prompt: "Endişenize neden olan nedir?",
    pixabayQuery: "worry+stress+anxiety",
  },
  DISAPPOINTED: {
    id: "disappointed",
    label: "Hayal Kırıklığına Uğramış",
    emoji: "😞",
    score: 3,
    color: "stone",
    prompt: "Ne beklediğiniz gibi gitmedi?",
    pixabayQuery: "disappointment+rain+grey",
  },
  FRUSTRATED: {
    id: "frustrated",
    label: "Hayal Kırıklığına Uğramış",
    emoji: "😤",
    score: 3,
    color: "orange",
    prompt: "İlerlemenizi ne engelliyor?",
    pixabayQuery: "frustrated+blocked+obstacle",
  },
  STRESSED: {
    id: "stressed",
    label: "Stresli",
    emoji: "😫",
    score: 3,
    color: "rose",
    prompt: "Size baskı yapan nedir?",
    pixabayQuery: "stress+pressure+overwhelmed",
  },
  INSECURE: {
    id: "insecure",
    label: "Güvensiz",
    emoji: "🥺",
    score: 2,
    color: "lime",
    prompt: "Kendinizden şüphe etmenize neden olan nedir?",
    pixabayQuery: "insecure+doubt+shadow",
  },
  SAD: {
    id: "sad",
    label: "Üzgün",
    emoji: "😢",
    score: 2,
    color: "cyan",
    prompt: "Sizi ne üzüyor?",
    pixabayQuery: "sad+melancholy+rain",
  },
  LONELY: {
    id: "lonely",
    label: "Yalnız",
    emoji: "🌙",
    score: 2,
    color: "zinc",
    prompt: "Başkalarıyla nasıl bağlantı kurabilirsiniz?",
    pixabayQuery: "lonely+solitude+night",
  },
  ANGRY: {
    id: "angry",
    label: "Kızgın",
    emoji: "😠",
    score: 1,
    color: "red",
    prompt: "Sizi ne sinirlendiriyor?",
    pixabayQuery: "angry+storm+thunder",
  },
};

export const getMoodTrend = (averageScore) => {
  if (averageScore >= 8) return "Harika hissediyorsunuz!";
  if (averageScore >= 6) return "Genel olarak iyi hissediyorsunuz.";
  if (averageScore >= 4) return "Fena değilsiniz.";
  if (averageScore >= 2) return "Zor zamanlar geçiriyorsunuz.";
  return "Zor bir dönemden geçiyorsunuz.";
};

export const getMoodById = (moodId) => {
  return MOODS[moodId?.toUpperCase()];
};